-- ============================================================================
-- Mas4U — Data-safety layer (Stage 1 of "office system")
-- Soft-delete (trash + restore) + accountability (who edited) + backups.
--
-- Additive and non-destructive: only ADDS columns/tables. Nothing is dropped,
-- no existing data changes. Safe to run once on the live project.
-- Apply this BEFORE deploying the matching app code (the app filters on
-- deleted_at, which must exist first).
-- ============================================================================

-- 1) Soft-delete: mark rows/tables as trashed instead of hard-deleting them.
alter table if exists public.data_tables add column if not exists deleted_at timestamptz;
alter table if exists public.data_rows  add column if not exists deleted_at timestamptz;

-- 2) Accountability: record who last touched a row (name is enough for display).
alter table if exists public.data_rows  add column if not exists updated_by text;

-- Fast filtering of "live" (non-deleted) rows per table.
create index if not exists data_rows_table_live_idx
  on public.data_rows (table_id) where deleted_at is null;
create index if not exists data_tables_live_idx
  on public.data_tables (sort_order) where deleted_at is null;

-- 3) Backups: periodic JSON snapshots of the shared app_state, for restore.
create table if not exists public.backups (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  kind        text not null default 'auto',   -- 'auto' | 'manual'
  note        text,
  created_by  text,
  data        jsonb not null
);
create index if not exists backups_created_at_idx on public.backups (created_at desc);

-- RLS: same posture as the rest of the app — any authenticated staff member.
-- (Role-based tightening comes in the RLS stage; this keeps parity for now.)
alter table public.backups enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='backups' and policyname='backups_authenticated_all') then
    create policy backups_authenticated_all on public.backups
      for all to authenticated using (true) with check (true);
  end if;
end $$;

-- Optional retention helper: keep only the newest 60 auto-backups.
-- (Call manually or from a scheduled job; not run automatically here.)
-- delete from public.backups where kind='auto' and id not in (
--   select id from public.backups where kind='auto' order by created_at desc limit 60
-- );
